#!/bin/bash
# 10 esimese arvu summa - liida ainult paarisarvud
#
summa=0
for (( i=1; i<=10; i++ )); do
    jaak=$((i % 2))
    if [ $jaak -eq 0 ]; then
        summa=$((summa + i))
    fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"  # Skripti lõpp
