#!/bin/bash

# Loome muutujad
aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks " 

# Loome lause
lause="$aasta$lause_keskosa$president"

# Väljastame lause ekraanile
echo $lause
