#!/bin/bash
echo -n "Mitu reisijat on?: "
read mitu_reisijat
echo -n "Mitu kohta on bussis?: "
read mitu_kohti

taidetud_bussid=$((mitu_reisijat / mitu_kohti))
maha_jaanud_reisijad=$((mitu_reisijat % mitu_kohti))

if [ $taidetud_bussid -eq 0 ] && [ $maha_jaanud_reisijad -gt 0 ]; then
    taidetud_bussid=1
    maha_jaanud_reisijad=0
fi

echo "Täielikult täidetud busside arv: $taidetud_bussid"
echo "Maha jäänud reisiad $maha_jaanud_reisijad "
