#!/bin/bash
#sisend kuu
echo -n "Sisesta kuu number (1-12): "
read kuu

if [ $kuu -eq 12 -o $kuu -eq 1 -o $kuu -eq 2 ]; then
echo "Praegu on talv"

elif [ $kuu -ge 3 -a $kuu -le 5 ]; then
echo "Praegu on kevad"

elif [ $kuu -ge 6 -a $kuu -le 8 ]; then
echo "Praegu on suvi"

elif [ $kuu -ge 9 -a $kuu -le 11 ]; then
echo "Praegu on sügis"

else

echo "Sellist numbrit kuus ei eksisteeri"
fi
